### PR TITLE
Add 2019-dinosaur-denver.md

### PR DESCRIPTION
**Pull request by zpipe07**
I've added a file for [DinosaurJS](https://dinosaurjs.org/) in Denver, CO.

### CODE REVIEW

**Comment by chriscoyier** [comment]
Looks like this conference is linking out to another conferences Code of Conduct. The issue there is that any attendee having a problem has nothing actionable they can do related to *this conference* when they find this. Can that be addressed?

**Comment by zpipe07** [comment]
I'm not affiliated with this conference, so excuse my ignorance, but it was my understanding that DinosaurJS is part of the JSConf family of events, so I assumed that JSConf's code of conduct would apply to DinoJS.

I noticed that JSConf.Asia linked to that same code of conduct, so this seemed appropriate.

Feel free to hold off until DinoJS creates their own CoC.

**Comment by chriscoyier** [comment]
Ah yeah if it's a JSConf event and they are using the JSConf CoC on their own site with some actionable stuff in there, it seems OK to go.

**Comment by chriscoyier** [comment]
The package.json lockfile is being weird on this branch. I'm gonna close and just add quick in a new PR.

**Pull request closed without merging**
