### PR TITLE
Add ColdFront in Copenhagen, Denmark

### PR DESCRIPTION
**Pull request by josephshambrook**

### CODE REVIEW

**Comment by chriscoyier** [comment]
Hey Joseph!

Conference looks awesome. Mr. @philhawksworth as host?! You're in for a treat, he's the best.

There is one thing to take care of here though. I'm not sure if you're the organizer or involved or what, so feel free to pass this message along if not. The Code of Conduct linked up just links to https://confcodeofconduct.com/ which is just a template for a Code of Conduct. There is nothing actionable or enforceable on there, meaning if someone at the conference had a problem, and was looking for help, they'd have no way to find it or any understanding of what could or would be done about it. 

I've heard from lots of folks who feel like this just isn't enough, and I agree with them. 

I wonder if we could get the organizing powers that be to take that a bit more seriously and post their own more comprehensive and considered Code of Conduct?

**Comment by josephshambrook** [comment]
Hey Chris! I'm not personally involved I'm afraid, just knew about it and thought I'd add it to your (excellent) site, but absolutely agree about the code of conduct. I'll try sending this over to the organisers, and will update here with any response I get.

**Comment by philhawksworth** [comment]
Thanks for the kind comments @chriscoyier! And although I know that the conference does take this seriously and has acted brilliantly in previous events, I do agree that this needs to be more explicit on the CoC on the site. I'll see if I can nudge the organising team to enhance the CoC as described.

**Comment by josephshambrook** [comment]
The conference has been cancelled, so no need for this PR anymore

https://2019.coldfront.co/cancellation/

**Pull request closed without merging**
