### PR TITLE
Add Pixels Camp v3.0

### PR DESCRIPTION
**Pull request by s3rgiosan**

### CODE REVIEW

**Comment by chriscoyier** [comment]
Could the code of conduct be linked to from the website? I see it mentions it, but there is no link to it.

**Comment by s3rgiosan** [comment]
I'm going to ask the organization team about it.

**Comment by s3rgiosan** [comment]
@chriscoyier I've updated the code of conduct link to https://pixels.camp/docs/code-of-conduct

**Comment by chriscoyier** [comment]
Thanks!

**Pull request merged**
