### PR TITLE
adding Script19

### PR DESCRIPTION
**Pull request by ddprrt**
Script'19 is the feelgood JavaScript conference in the heart of Austria. 100% community driven and nice <3

### CODE REVIEW

**Comment by ddprrt** [comment]
@chriscoyier I see that the apostrophe causes some errors... shall I fix it in the data?

**Comment by chriscoyier** [comment]
I see that's the real name of the conference, so probably better if we fix it at the build level.

**Comment by ddprrt** [comment]
Alright 👍 

Otherwise I'd done something like that:

```
---
title: "Script'19"
---```
That's usually how I tame YAML :D

**Comment by chriscoyier** [comment]
The PNG filename problem is fixed, but the SVG is still problematic. 

```
7:15:58 AM: failed during stage 'deploying site': Invalid filename 'teasers/svg/script&#39;19.svg'. Deployed filenames cannot contain # or ? characters
```

I think `teasers/svg/script&#39;19.svg` is created from Eleventy itself at build time, from /site/teasers/index.njk`, which has:

```
permalink: teasers/svg/{{ pagination.items[0].data.title | slug }}.svg
```

That needs to get filtered somehow to remove the single quote (escaped or not). 

Probably needs to happen in the `.eleventy.js` file somehow.  Thoughts perhaps @Wilto?

**Comment by ddprrt** [comment]
@chriscoyier I did override the slug filter in `.eleventy.js`. It uses the same package, but is more restrictive to exclude parenthesis and apostrophes.

**Comment by chriscoyier** [comment]
Great, thanks for the help!

**Pull request merged**
