### PR TITLE
Create 2021-central-wisconsin-it-conference

### PR DESCRIPTION
**Pull request by jevenson**
Added entry for the 2021 Central Wisconsin IT Conference

### CODE REVIEW

**Comment by chriscoyier** [comment]
Hey hey my home state!

Thanks for the effort here - but it doesn't really look like a front-end focused conference? Or is it?

**Comment by jevenson** [comment]
Wisconsin represent! We'd love to have you speak if you're interested!

Yeah, we're not 100% focused on front end, sorry I didn't realize that was a requirement. We were on the site in 2019 fwiw.

Totally understandable if you want me to close this out.
________________________________

**Comment by chriscoyier** [comment]
Meh, that's OK, let's roll with it. There are so few conferences these days it's nice to see stuff on the board. If things really get rolling again, I do want to scope this site to front-end specific ones, but it's not like of critical importance ;)

**Comment by jevenson** [comment]
Thanks @chriscoyier, we appreciate it!

**Pull request merged**
