### PR TITLE
Adds Coldfront Conference

### PR DESCRIPTION
**Pull request by kimblim**

### CODE REVIEW

**Comment by chriscoyier** [comment]
Hey thanks @kimblim!

There have been a lot of conferences submitted that just link out to http://confcodeofconduct.com/ for the CoC, as this one does. I've gotten a lot of feedback that is problematic. One big reason is that it isn't actionable for attendees of the specific conference. Say an attendee is having a problem, they go to the site, find this... it doesn't help them figure out what to do.

Can this be addressed?

**Comment by kimblim** [comment]
Hey,

I'll ping the organizers with this PR (I just got an email that it was happening, and have nothing to do with the conference myself). I'll leave it up to them to do something about it.

**Comment by chriscoyier** [comment]
Looks like they are kind of ignoring having an actionable code of conduct, so I'll just close.

**Comment by kimblim** [comment]
Yup, I did try reaching out to them but they never responded.

**Pull request closed without merging**
